// 提交试卷
export const SUBMIT_PAPER_REQUEST = 'SUBMIT_PAPER_REQUEST';
export const SUBMIT_PAPER_SUCCESS = 'SUBMIT_PAPER_SUCCESS';
export const SUBMIT_PAPER_FAIL = 'SUBMIT_PAPER_FAIL';

// 清除错误
export const CLEAR_PAPER_ERRORS = 'CLEAR_PAPER_ERRORS';
